"""
Shared plumbing for the 2D field-controlling tutorial series.

This module deliberately contains **only boilerplate**: paths, constants, model
factories and checkpoint IO. Everything that is *scientific mechanism* -- how the
porosity field is computed, how the Gaussian process is fitted, how the paired
training batches are built, how conditioning is applied at inference -- is written
out inline in the notebook where it is being taught, so that nothing important
hides behind an import.

The 2D setting mirrors the 3D thesis pipeline (`pipelines/fieldcontrolled/`)
one-for-one:

    thesis (3D)                        tutorial (2D)
    ---------------------------------  -----------------------------------
    1000^3 micro-CT volume             1000^2 slices of a 1000^3 volume
    256^3 training subvolume           256^2 training patch
    48 cube symmetries                 8 square symmetries (D4)
    w = 129 / 257 cubic window         w = 129 square window
    VAE F = 8, C_l = 4                 VAE F = 8, C_l = 4
    latent conditioning field 32^3     latent conditioning field 32^2
    border crop b = 128 (= R for 257)  border crop b = 64 (= R for 129)
"""
import os

import numpy as np
import torch

import diffsci2.models
import diffsci2.nets

# =============================================================================
# Paths
# =============================================================================

REPO_ROOT = "/home/ubuntu/repos/DiffSci2"
TUTORIAL_DIR = os.path.join(REPO_ROOT, "notebooks", "tutorials", "fieldcontrolling")

# All tutorial artifacts (arrays, fitted GP parameters, checkpoints, figures)
# live here. The directory is gitignored -- it is regenerated by the notebooks.
DATA_DIR = os.path.join(TUTORIAL_DIR, "fcdata")
CKPT_DIR = os.path.join(DATA_DIR, "checkpoints")
FIG_DIR = os.path.join(DATA_DIR, "figures")

VAE_CKPT_DIR = os.path.join(CKPT_DIR, "vae")
SCALAR_CKPT_DIR = os.path.join(CKPT_DIR, "scalar")
FIELD_CKPT_DIR = os.path.join(CKPT_DIR, "field")

# Raw rock. Berea sandstone, 1000^3 binary volume at 2.25 um, solid = 1, pore = 0.
RAW_PATH = os.path.join(
    REPO_ROOT, "saveddata", "raw", "eleven_sandstones", "Berea_2d25um_binary.raw"
)
VOLUME_SHAPE = (1000, 1000, 1000)
STONE = "Berea"
VOXEL_SIZE_UM = 2.25

# Artifacts produced by notebook 01 and consumed by 02-05.
SLICES_PATH = os.path.join(DATA_DIR, "berea_slices.npy")            # uint8  [N, 1000, 1000]
FIELD_PATH = os.path.join(DATA_DIR, "berea_field_w129.npy")         # float16 [N, 1000, 1000]
GP_PATH = os.path.join(DATA_DIR, "berea_gp_w129_latent.npz")        # fitted Matern parameters


# =============================================================================
# Constants -- the 2D mirror of the thesis configuration
# =============================================================================

# --- data ---
N_SLICES = 160          # number of z-slices lifted out of the 1000^3 volume
TRAIN_SLICES = 120      # slices [0:120] train, [120:160] validation (thesis: 700/300)

# --- porosity field ---
WINDOW = 129            # averaging window w (thesis compares w = 129 and w = 257)
RADIUS = (WINDOW - 1) // 2   # R = 64; the inward crop that makes the field self-contained

# --- autoencoder ---
F = 8                   # spatial compression factor
Z_DIM = 4               # latent channels C_l
VAE_PATCH = 128         # VAE is trained on 128^2 patches (and generalizes to larger)

# --- diffusion ---
PATCH = 256                     # diffusion training patch (pixel space)
LATENT_PATCH = PATCH // F       # 32 -- also the size of the conditioning field
MODEL_CHANNELS = 64
NSTEPS = 21                     # Heun steps for the probability-flow ODE
SIGMA_MIN, SIGMA_MAX, SIGMA_DATA = 0.002, 80.0, 0.5
INITIAL_NORM = 20.0

# --- inference ---
BORDER = 64             # border crop b, matched to the averaging radius R
COARSE_N = 32           # coarse grid on which the GP is sampled exactly

# --- hardware ---
DEVICE = "cuda:2"       # NEVER cuda:7 unless explicitly authorised


def ensure_dirs():
    for d in [DATA_DIR, CKPT_DIR, FIG_DIR, VAE_CKPT_DIR, SCALAR_CKPT_DIR, FIELD_CKPT_DIR]:
        os.makedirs(d, exist_ok=True)
    gitignore = os.path.join(DATA_DIR, ".gitignore")
    want = ("# Tutorial artifacts are regenerated by the notebooks.\n"
            "*\n"
            "!.gitignore\n")   # keep the rule itself tracked, or a fresh clone loses it
    if not os.path.exists(gitignore) or open(gitignore).read() != want:
        with open(gitignore, "w") as fh:
            fh.write(want)


# =============================================================================
# Model factories
# =============================================================================

def make_vae_config(resolution=VAE_PATCH):
    """2D VAE with compression factor F = 8 (three downsamplings) and C_l = 4.

    `ch_mult` has four entries, and the VAE downsamples at every level but the
    last, so F = 2^(len(ch_mult) - 1) = 8 -- the same factor as the 3D production
    autoencoder.
    """
    return diffsci2.nets.VAENetConfig(
        dimension=2,
        in_channels=1,
        out_channels=1,
        z_channels=Z_DIM,
        z_dim=Z_DIM,
        ch=32,
        ch_mult=[1, 2, 4, 4],     # -> F = 8
        num_res_blocks=2,
        attn_resolutions=[],
        dropout=0.0,
        resolution=resolution,
        has_mid_attn=False,       # no attention anywhere: keeps the RF finite
        resamp_with_conv=True,
        attn_type="vanilla",
        tanh_out=False,
        input_bias=True,
        output_bias=True,
        with_time_emb=False,
        double_z=True,
        num_groups=32,
        patch_size=None,
        memory_efficient_variant=False,
        use_flash_attention=True,
        minimal_rf_mode=False,
    )


def make_vae(resolution=VAE_PATCH):
    """Fresh (untrained) VAEModule."""
    net = diffsci2.nets.VAENet(config=make_vae_config(resolution))
    return diffsci2.models.VAEModule(
        config=diffsci2.models.VAEModuleConfig(), encdec=net
    )


def make_punet_config(cond_dropout=0.1):
    """2D PUNetG mirroring the 3D production configuration used in the thesis.

    Fully convolutional, no self-attention -- which is exactly what makes the
    model shift-invariant and free of spurious long-range correlations, the
    architectural assumption the field-controlling argument rests on.
    """
    return diffsci2.nets.PUNetGConfig(
        input_channels=Z_DIM,
        output_channels=Z_DIM,
        dimension=2,
        model_channels=MODEL_CHANNELS,
        channel_expansion=[2, 4],
        number_resnet_downward_block=2,
        number_resnet_upward_block=2,
        number_resnet_attn_block=0,        # 0 -> no attention at all
        number_resnet_before_attn_block=3,
        number_resnet_after_attn_block=3,
        kernel_size=3,
        in_out_kernel_size=3,
        in_embedding=False,
        time_projection_scale=10.0,
        input_projection_scale=1.0,
        transition_scale_factor=2,
        transition_kernel_size=3,
        dropout=0.1,
        cond_dropout=cond_dropout,
        first_resblock_norm="GroupLN",
        second_resblock_norm="GroupRMS",
        affine_norm=True,
        convolution_type="default",
        num_groups=1,
        attn_residual=False,
        attn_type="default",
        bias=True,
    )


def make_flow_model(conditional=True, cond_dropout=0.1):
    """PUNetG denoiser. `conditional=False` builds the same network without the
    conditioning embedder -- which is how the *implicit unconditional* model of
    the thesis is obtained from the very same weights (generation case 7)."""
    if conditional:
        embedder = diffsci2.nets.ScalarEmbedder(dembed=MODEL_CHANNELS, key="porosity")
    else:
        embedder = None
    return diffsci2.nets.PUNetG(
        make_punet_config(cond_dropout), conditional_embedding=embedder
    )


def make_si_module(model, autoencoder=None):
    """EDM-parameterised score-interpolant module, same settings as the pipeline."""
    config = diffsci2.models.SIModuleConfig.from_edm_sigma_space(
        sigma_min=SIGMA_MIN,
        sigma_max=SIGMA_MAX,
        sigma_data=SIGMA_DATA,
        initial_norm=INITIAL_NORM,
        loss_formulation="denoiser",
    )
    return diffsci2.models.SIModule(
        config=config, model=model, autoencoder=autoencoder
    )


# =============================================================================
# Checkpoint IO
# =============================================================================

def _strip_prefix(state_dict, prefix):
    return {k[len(prefix):]: v for k, v in state_dict.items() if k.startswith(prefix)}


def load_vae(ckpt_path=None, device=None):
    """Rebuild the tutorial VAE and load trained weights (notebook 00)."""
    if ckpt_path is None:
        ckpt_path = os.path.join(VAE_CKPT_DIR, "last.ckpt")
    module = make_vae()
    state = torch.load(ckpt_path, map_location="cpu", weights_only=False)["state_dict"]
    module.load_state_dict(state)
    module.eval()
    if device is not None:
        module.to(device)
    return module


def load_flow_weights(ckpt_path):
    """Pull the bare denoiser weights out of a Lightning SIModule checkpoint."""
    state = torch.load(ckpt_path, map_location="cpu", weights_only=False)["state_dict"]
    return _strip_prefix(state, "model.")


def load_flow_model(ckpt_path, conditional=True, device=None):
    """Rebuild the denoiser and load trained weights.

    Passing `conditional=False` loads the *same* weights into a network with no
    conditioning embedder, giving the implicit unconditional model.
    """
    model = make_flow_model(conditional=conditional)
    weights = load_flow_weights(ckpt_path)
    if not conditional:
        weights = {k: v for k, v in weights.items()
                   if not k.startswith("conditional_embedding.")}
    missing, unexpected = model.load_state_dict(weights, strict=False)
    if conditional and (missing or unexpected):
        raise RuntimeError(f"checkpoint mismatch: missing={missing} unexpected={unexpected}")
    model.eval()
    if device is not None:
        model.to(device)
    return model


# =============================================================================
# Small helpers used across notebooks
# =============================================================================

def load_slices(mmap=True):
    """Binary slices produced by notebook 01. Convention: solid = 1, pore = 0."""
    return np.load(SLICES_PATH, mmap_mode="r" if mmap else None)


def load_fields(mmap=True):
    """Porosity fields aligned voxel-for-voxel with `load_slices()`."""
    return np.load(FIELD_PATH, mmap_mode="r" if mmap else None)


def porosity_of(binary):
    """Pore fraction of a binary array under the solid = 1 convention."""
    return float(1.0 - np.asarray(binary).mean())


# --- the porosity field, one canonical definition -----------------------------
# Notebook 01 defines these inline, because computing the field is what it teaches.
# The copies here are what notebooks 03-05 import, so that the *realised* field of a
# generated image is computed exactly the way the conditioning field was, and the two
# are comparable. Both mirror scripts/old/0007-porosity-field-evaluation.py:
#     calculate_porosity_field_full(volume, kernel_size) -> average_volume(field, F)

def porosity_field_valid(binary, window=None):
    """Local pore fraction, 'valid' convolution. Shape shrinks by (window - 1)."""
    import scipy.signal
    window = WINDOW if window is None else window
    kernel = np.ones((window, window), dtype=np.float32) / window ** 2
    pore = 1.0 - np.asarray(binary, dtype=np.float32)
    return scipy.signal.fftconvolve(pore, kernel, mode='valid')


def porosity_field_full(binary, window=None):
    """Local pore fraction, 'same' convolution with boundary-count normalisation.

    Values within `window // 2` of the border are averaged over fewer than
    window**2 real voxels; crop inward by that radius before trusting them.
    """
    import scipy.signal
    window = WINDOW if window is None else window
    pore = 1.0 - np.asarray(binary, dtype=np.float32)
    numerator = scipy.signal.fftconvolve(
        pore, np.ones((window, window), dtype=np.float32), mode='same')
    count_h = scipy.signal.fftconvolve(np.ones(pore.shape[0]), np.ones(window), mode='same')
    count_w = scipy.signal.fftconvolve(np.ones(pore.shape[1]), np.ones(window), mode='same')
    return numerator / (count_h[:, None] * count_w[None, :])


def to_latent(field, factor=None):
    """Average-pool a pixel-resolution field down to the latent grid."""
    import torch.nn.functional as F_
    factor = F if factor is None else factor
    t = torch.from_numpy(np.ascontiguousarray(field, dtype=np.float32))[None, None]
    return F_.avg_pool2d(t, kernel_size=factor, stride=factor)[0, 0].numpy()


def realised_field(binary, window=None, factor=None):
    """The porosity field a generated (or real) binary image actually has.

    IMPORTANT: this is a window-`window` local average, *then* pooled by `factor`.
    Pooling the binary image straight down by `factor` is a different quantity --
    the pore fraction of each factor x factor block, i.e. a window-8 field -- and
    is not comparable to the window-129 conditioning field.
    """
    return to_latent(porosity_field_full(binary, window), factor)


def field_interior(field_latent, window=None, factor=None):
    """Drop the belt where the 'same'-mode field saw fewer than window**2 voxels."""
    window = WINDOW if window is None else window
    factor = F if factor is None else factor
    m = ((window - 1) // 2) // factor
    return field_latent[m:-m, m:-m] if m > 0 else field_latent


def gaussian_hellinger(p, q):
    """Closed-form Hellinger distance between Gaussian fits of two sample sets.

    This is Eq. (Hellinger) of Part II, used there to score sub-block diversity.
    """
    mp, sp = float(np.mean(p)), float(np.std(p))
    mq, sq = float(np.mean(q)), float(np.std(q))
    var = sp ** 2 + sq ** 2
    if var <= 0:
        return 0.0
    h2 = 1.0 - np.sqrt(2.0 * sp * sq / var) * np.exp(-((mp - mq) ** 2) / (4.0 * var))
    return float(np.sqrt(max(h2, 0.0)))


def savefig(fig, name, dpi=160):
    """Save a figure as both PDF (for LaTeX) and PNG (for slides)."""
    ensure_dirs()
    for ext in ("pdf", "png"):
        fig.savefig(os.path.join(FIG_DIR, f"{name}.{ext}"), dpi=dpi, bbox_inches="tight")
    return os.path.join(FIG_DIR, name)
